name: btcan_viewer
description: BLE CAN viewer for ESP32-C6 BTCAN sniffer
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_blue_classic: ^0.1.0
  usb_serial: ^0.5.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
